name: Report a problem/bug
title: '[Problem/Bug]: '
description: Report if something is not working
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: 
      Thanks for taking time to fill up the bug report! Here is [a good bug report](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3648) that will help us in identifying the issue.
- id: what-happened
  type: textarea
  attributes:
    description: Describe the issue you encountered. Callstacks and error messages are helpful.
    label: What happened?
  validations:
    required: true
- id: importance
  type: dropdown
  attributes:
     label: Importance
     description: How important is this bug to your app?
     multiple: false
     options:
       - ----Please select----
       - Blocking. My app's basic functions are not working due to this issue.
       - Important. My app's user experience is significantly compromised.
       - Moderate. My app's user experience is affected, but still usable.
  validations:
      required: true
- id: runtime-channel
  type: dropdown
  attributes:
     label: Runtime Channel
     description: Are you seeing this issue in stable release or prerelease of WebView2 runtime?
     multiple: true
     options:
       - Stable release (WebView2 Runtime)
       - Prerelease (Edge Canary/Dev/Beta)      
  validations:
      required: true
- type: markdown
  attributes:
    value: |
          **Tip:** it's recommended to test your web content in the WebView2 control against [Microsoft Edge Insider (preview) Channels (Beta, Dev, or Canary)](https://www.microsoft.com/en-us/edge/download/insider?form=MA13FJ). For more information please check out [testing app for forward-compatibility](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#test-your-app-for-forward-compatibility).
- id: runtime-version
  type: input
  attributes:
    description: Which runtime version are you using? Instructions [here](https://github.com/MicrosoftEdge/WebView2Feedback/blob/victorhuangwq/updatetemplate/diagnostics/version.md)
    label: Runtime Version
    placeholder: (eg. 114.0.1823.79)
- id: sdk-version
  type: input
  attributes:
    description: Which SDK version are you using?  Instructions [here](https://github.com/MicrosoftEdge/WebView2Feedback/blob/victorhuangwq/updatetemplate/diagnostics/version.md)
    label: SDK Version
    placeholder: (eg. 1.0.1905-prerelease)

- id: framework
  type: dropdown
  attributes:
    description: What UI framework are you using?
    label: Framework
    options:
    - ----Please select----
    - WPF
    - Win32
    - Winforms
    - WinUI2/UWP
    - WinUI3/WinAppSDK
    - Unity Plugin
    - Other
  validations:
    required: true
- id: os
  type: dropdown
  attributes:
    description: Which operating system are you seeing this issue with?
    label: Operating System
    multiple: true
    options:
    - Windows 10
    - Windows 11
    - Earlier than Windows 10 (deprecated)
    - Windows Server
    - Xbox
    - Hololens
    - Other
  validations:
    required: true

- id: os-version
  type: input
  attributes:
    description: Version can be found in System > About or System Information
    label: OS Version
    placeholder: (e.g. 22621.2283 or 10.0.22621)
  validations:
    required: false
- id: repro-steps
  type: textarea
  attributes:
    description: What are the steps needed to reproduce the bug? Describe the expected behavior against the actual behavior.
    label: Repro steps
  validations:
    required: true
- id: repro-in-edge
  type: dropdown
  attributes:
    description: Does this issue reporduce in the Edge or Chrome browsers?
    label: Repros in Edge Browser
    multiple: true
    options:
    - 'No'
    - 'Yes, in Stable'
    - 'Yes, in Beta'
    - 'Yes, in Dev'
    - 'Yes, in Canary'
    - 'Yes, in Chrome'
    - Not Applicable
  validations:
    required: true
- id: regression
  type: dropdown
  attributes:
    description: Was this working before, but has regressed?
    label: Regression
    options:
    - No, this never worked
    - Regression in newer Runtime
    - Regression in newer SDK
    - Don't know
  validations:
    required: true
- id: last-working-version
  type: input
  attributes:
    description: If this is a regression, what was the last working version of SDK and Runtime?
    label: Last working version (if regression)
    placeholder: (e.g. SDK 1.0.1774.30, Runtime 114.0.1823.32)
  validations:
    required: false
