name: Auto Assign
on:
  issues:
    types: [labeled]
jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      issues: write
    
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: ambikakunnath
          includeLabels: regression
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: ambikakunnath
          includeLabels: bluescreen
