name: Run Azure Login with OIDC
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Sync to ADO
        uses: champnic/github-actions-issue-to-work-item@testManagedIdentities
        with:
          ado_organization: 'microsoft'
          ado_project: 'Edge'
          ado_area_path: 'Edge\Web Experience\WebView2'
