name: Run test action

on:
  workflow_dispatch
  # issues:
  #  types: [labeled, closed, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  alert:
    runs-on: windows-latest
    name: Syncing to Azure DevOps
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Sync to ADO
      uses: champnic/github-actions-issue-to-work-item@simple-sync-azurecli
      env:
        github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
      with:
        label: 'test'
        ado_organization: 'microsoft'
        ado_project: 'Edge'
        ado_area_path: 'Edge\Web Experience\WebView2'
        ado_tags: 'WV2_GitHub'
        ado_gh_closed_tag: 'WV2_GitHub_Closed'
