name: “Notify Regression Issue to Teams”

on:
  issues:
    types: [opened]

jobs:
  send-to-teams:
    runs-on: ubuntu-latest
    # only run when the new issue has a label called "regression"
    if: contains(github.event.issue.labels.*.name, 'regression')

    steps:
      - name: Prepare Teams payload
        run: |
          cat <<EOF > teams_payload.json
          {
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "themeColor": "FF0000",
            "summary": "Regression issue opened",
            "sections": [
              {
                "activityTitle": "🚨 Regression Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}",
                "activitySubtitle": "opened by @${{ github.event.issue.user.login }}",
                "facts": [
                  { "name": "Repository", "value": "${{ github.repository }}" },
                  { "name": "Link",       "value": "${{ github.event.issue.html_url }}" }
                ],
                "text": "${{ github.event.issue.body }}"
              }
            ]
          }
          EOF

      - name: Send to Teams channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -d @teams_payload.json \
               "$TEAMS_WEBHOOK_URL"
