name: get issue summary of last week

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 1'
  
jobs:
  alert:
    runs-on: ubuntu-latest
    name: get summary
    steps:
    - uses: shangminx/Auto-Digest@main
      id: getsummary
      with:
        daily_or_weekly: 'weekly'
    - uses: shangminx/Auto-Digest/sendEmail@main
      id: sendEmail
      with: 
        email_password: ${{ secrets.EMAIL_PASSWORD }}
        sender_email:  ${{secrets.SENDER_EMAIL}}
        recipient_email: ${{secrets.RECIPIENT_EMAIL}}
        report_data: ${{ steps.getsummary.outputs.dailysummary }}
    - uses: plantree/github-actions-issue-notify-teams@main
      with:
        type: weekly-report
        message: ${{ steps.getsummary.outputs.dailysummary }}
        webhook: ${{ secrets.WEBHOOK }}
